# -*- coding: utf-8 -*-
"""Predictive_Analysis-2A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BG8JOWwEz_ep_64X73kRVDNnHQFRk9E
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score,confusion_matrix

df=pd.read_csv('/content/booking.csv')
df

df.shape

df.duplicated().sum()

df.isna().sum()

room_typ=df['room type'].mode()[0]
df['room type']=df['room type'].fillna(room_typ)
avg=df['average price'].mean()
df['average price']=df['average price'].fillna(avg)

df.isna().sum()

df

df['type of meal']=df['type of meal'].str.replace(" ","_")
df['room type']=df['room type'].str.replace(" ","_")



# no outliers found

le=LabelEncoder()
for i in df.select_dtypes(include='object').columns:
  df[i]=le.fit_transform(df[i])

df

X =df.drop('booking status',axis=1)
y= df['booking status']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

scaler= StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

log_reg=LogisticRegression()
model = LogisticRegression()
model.fit(X_train_scaled,y_train)
y_pred=model.predict(X_test_scaled)

acc=accuracy_score(y_test,y_pred)
print(f'Accuracy is {acc}')
acc=f1_score(y_test,y_pred)
print(f'F1_score is {acc}')
acc=precision_score(y_test,y_pred)
print(f'Precision Score is {acc}')
acc=recall_score(y_test,y_pred)
print(f'Recall Score is {acc}')

con=confusion_matrix(y_test,y_pred)
print(f'Confusion Matrix is {con}')

