# -*- coding: utf-8 -*-
"""Final_assessment-4A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ebfXEipiSJEBg6V1BkNNIypAMpmsrO8
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.ensemble import IsolationForest
from sklearn.cluster import DBSCAN

df=pd.read_csv('/content/anomaly_train.csv')
df

df.info()

df.isna().sum()

df.duplicated().sum()

df.info()

le=LabelEncoder()
df['Type']=le.fit_transform(df['Type'])
df['Location']=le.fit_transform(df['Location'])

X=df.drop('TransactionID',axis=1)
sns.pairplot(pd.DataFrame(X), diag_kind='kde')
plt.show()
cols=['Amount','Location']
X=X[cols]

sns.pairplot(pd.DataFrame(X), diag_kind='kde')
plt.show()

model = IsolationForest(random_state=42)
model.fit(X)

outliers = model.predict(X)
outliers

plt.figure(figsize=(10, 6))
plt.scatter(X['Amount'], X['Location'], c=outliers, marker='o', cmap=plt.cm.coolwarm)
plt.title('Isolation Forest Outlier Detection')
plt.xlabel(cols[0])
plt.ylabel(cols[1])
plt.grid(True)
plt.colorbar()
plt.show()

