# -*- coding: utf-8 -*-
"""Second_assessment_2A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-BPetL2w09p3yxRqE29lFDZoPdMXK4J
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans

df=pd.read_csv('/content/Mall_Customers.csv')
df

df.isna().sum()

df['Annual Income (k$)']=df['Annual Income (k$)'].fillna(df['Annual Income (k$)'].mean())

df.isna().sum()

df.duplicated().sum()

le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])

scaler=StandardScaler()
x=df.drop('CustomerID',axis=1)
df=pd.DataFrame(scaler.fit_transform(x),columns=x.columns)

kmeans=KMeans(n_clusters=3,init='k-means++')
y_pred=kmeans.fit_predict(df)
df['Cluster']=y_pred
print(kmeans.cluster_centers_)
df1=df[df.Cluster==0]
df2=df[df.Cluster==1]
df3=df[df.Cluster==2]
plt.scatter(df1['Annual Income (k$)'],df1['Spending Score (1-100)'],color='green')
plt.scatter(df2['Annual Income (k$)'],df2['Spending Score (1-100)'],color='red')
plt.scatter(df3['Annual Income (k$)'],df3['Spending Score (1-100)'],color='black')
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],color='purple',marker='*',label='centroid')
plt.xlabel('AgeGroup')
plt.ylabel('Spend')
plt.legend()
plt.show()

from sklearn.metrics import silhouette_score
sse = []
sil_score=[]
k_nrg=range(1,10)
for k in range(1,10):
   kmeans = KMeans(n_clusters=k)
   kmeans.fit(df)
   sse.append(kmeans.inertia_)
   if k>=2:
    x=silhouette_score(df, kmeans.fit_predict(df))
    sil_score.append(x)
plt.xlabel('K')
plt.ylabel('Sum of squared error')
plt.plot(sse)
plt.show()
plt.xlabel('K')
plt.ylabel('Silhouette Score')
plt.plot(range(2,10),sil_score,color='red')
plt.show()

