# -*- coding: utf-8 -*-
"""Question-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aDqmRsVatOWsRRULVMT3kLyUpLXMHKyw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RANSACRegressor
from sklearn.metrics import accuracy_score,r2_score,precision_score,recall_score,confusion_matrix,f1_score,mean_absolute_error,mean_squared_error,silhouette_score
import warnings
warnings.filterwarnings('ignore')

#Importing of data
df=pd.read_csv('/content/bengaluru_house_prices.csv')
df

df.info()

# calculating the shape of the data
df.shape

df.describe()

#convert total_sqft column to quantiable
def convert_to_int(value):
    try:
        if ' - ' in value:
            low, high = value.split(' - ')
            return int((float(low) + float(high)) / 2)
        elif '.' in value:
            return int(float(value))
        else:
            return int(value)
    except:
        return np.nan
df['total_sqft'] = df['total_sqft'].apply(convert_to_int)

print(df)

# checking for null values
df.isna().sum()

#Changing object into integer
df['total_sqft']=pd.to_numeric(df['total_sqft'],errors='coerce')

# Plot histograms for numerical columns
for i in df.select_dtypes(include=['float64', 'int64']).columns:
    plt.figure(figsize=(10, 5))
    sns.histplot(df[i])
    plt.title(f'Histogram of {i}')
    plt.xlabel(i)
    plt.ylabel('Frequency')
    plt.show()

# Plot bar charts for categorical columns
for column in df.select_dtypes(include=['object']).columns:
    plt.figure(figsize=(10, 5))
    df[column].value_counts().plot(kind='bar')
    plt.title(f'Bar Chart of {column}')
    plt.xlabel(column)
    plt.ylabel('Count')
    plt.show()

#Checking for Duplicate rows
df.duplicated().sum()

#Handling Null values
for i in df.select_dtypes(include=['int64','float64']).columns:
  df[i]=df[i].fillna(df[i].mean())
for i in df.select_dtypes(include='object').columns:
  df[i]=df[i].fillna(df[i].mode()[0])

#Again checking for null values
df.isna().sum()

#dropping duplicate values
df=df.drop_duplicates()

# Compute the correlation matrix for numerical variables
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
correlation_matrix = df[numerical_columns].corr()
print("Correlation matrix:\n", correlation_matrix.to_string())

# Plot the correlation matrix as a heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f")
plt.title('Heatmap of Correlation Matrix')
plt.show()

# Generate scatter plots for pairs of numerical variables
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns
for i in range(len(numerical_columns)):
    for j in range(i + 1, len(numerical_columns)):
        plt.figure(figsize=(10, 6))
        sns.scatterplot(data=df, x=numerical_columns[i], y=numerical_columns[j])
        plt.title(f'Scatter Plot between {numerical_columns[i]} and {numerical_columns[j]}')
        plt.show()

#check for outliers
for c in df.select_dtypes(include=['int64','float64']).columns:
  plt.figure(figsize=(10,5))
  sns.boxplot(x=df[c])

#Outlier Handling
for c in df.select_dtypes(include=['int64','float64']).columns:
  q1 = df[c].quantile(0.25)
  q3 = df[c].quantile(0.75)
  iqr = q3-q1
  lwr = q1-1.5*iqr
  upr = q3+1.5*iqr
  df.loc[df[c]>upr,c]=upr
  df.loc[df[c]<lwr,c]=lwr

#checking again for outliers
for c in df.select_dtypes(include=['int64','float64']).columns:
  plt.figure(figsize=(10,5))
  sns.boxplot(x=df[c])

le=LabelEncoder()
for i in df.select_dtypes(include='object').columns:
  df[i]=le.fit_transform(df[i])

df

# here Price is target feature so we drop it from features column
# y is the
X=df.drop(columns='price')
y=df['price']
#X contains all the feature columns

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

model=LinearRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

r2score=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
print(r2score,mae,mse)

#We can predict prices of houses in bangalore