# -*- coding: utf-8 -*-
"""Internal_assessment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_K3l5de9f7-SBFiyxW5Hctsa1uoNkKgr
"""

#1
def area_c(area1):

  if area>50000:
    print('Size of the property is Large')
  elif area<=50000 and area >20000:
    print('Size of the property is Medium')
  else:
    print('Size of the property is Small')

length=float(input())
width=float(input())
area=length*width
area_c(area)

#2
def plan_diet(bmi_score):
  if bmi_score <22:
    print('The person is calorie deficient and needs to eat more.')
  elif bmi_score>22 and bmi_score<25:
    print('The person is fit and can follow his routine')
  if bmi_score >25:
    print('The person should be very careful towards the diet.')
height=float(input())
weight=float(input())
bmi_score=weight/(height**2)
plan_diet(bmi_score)

#3
#name=input()
#grade=input()
#subject=input()
dic={'name':'rohit','maths':'A','social':'B','science':'C'}
print(dic)

#4
age=int(input())
movie_content_rating=input()
if age<=12 and movie_content_rating == 'U':
  print('These are the movies for kids')
elif age>12 and age<20 and (movie_content_rating =='U' or movie_content_rating == 'U/A'):
  print('These are the movies for teens')
elif age >=20 and age<60 :
  print('These are the movies for adults')
elif age>60:
  print('These are the movies for senior')
else:
  print('These Movies should not be watch for ',+age)

#5
lst=[0,1,2,3,4,5,6,7,8,9]
even_id=[]
i=0
for i in lst:
  if i%2==0:
    even_id.append(i)
print(even_id)

#6
user_password='Hemanth@#$%1234'
print('please enter the password')
password=input()

if password==user_password:
  print('You can access the files')
else:
  password_correction(password)
  if password==user_password:
    print('You can access the files')
  else:
    print('Your are denied of access')

def password_correction(password):
  print('please re-enter the correct password')
  password=input()

#7
def remarks(avg_score):
  avg_score=(customer_rating+customer_service_rating+customer_ambience_rating+customer_quality_rating)/4
  if avg_score<5:
    print('Need to improve a lot')
  elif avg_score>5 and avg_score<8:
    print('There must be a better resolution to work for better performances')
  else:
    print('This must be maintained to get more customers')

customer_rating=float(input())
customer_service_rating=float(input())
customer_ambience_rating=float(input())
customer_quality_rating=float(input())
avg_score=(customer_rating+customer_service_rating+customer_ambience_rating+customer_quality_rating)/4
remarks(avg_score)

#8
stra='Hi Iam Hemanth srikar '
count=0
str_lst=list(stra)
print(str_lst)
lst=['a','e','i','o','u','A','E','I','O','U']
for i in str_lst:
  for j in lst:
    if i==j:
      count= count+1
print(count)

#9

#10

#11
name=input()
if type(name)==str:
  pass
else:
  print("enter valid name")
age=(input())
if type(age)==int:
  pass
else:
  print('enter valid age')

