# -*- coding: utf-8 -*-
"""Final_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fd0xL8kz2kEGnWXJTsPQ9uZz5K10E0tY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#1a
dataset=pd.read_csv('/content/Final Dataset - IPL.csv')
dataset

#1b
x=np.shape(dataset)
print(x)
# by analyzing the dataset , there are no null values in the dataset.

#2a,2b
# here to check if the data has any null values or not is necessary before performing any simplification.
# There are no null values in the dataset.
arr=dataset['match_id'].value_counts()
print(arr)
# here every match_id is unique and does not have any duplicate values in the dataset
# so the dataset is ready for the execution and can be used for any other purposes.

#3a
arr=np.mean(dataset['first_ings_score'])
print('The mean of first_ininngs_score in the ipl is',arr)
arr1=np.median(dataset['first_ings_score'])
print('The median of first_ininngs_score in the ipl is',arr1)
arr2=dataset['first_ings_score'].value_counts().head(4)
print('These are the most repeated score in the ipl:', arr2)
arr3=np.std(dataset['first_ings_score'])
print('It is the standard deviation of the first inings score:', arr3)
arr4=np.max(dataset['first_ings_score'])
arr5=np.min(dataset['first_ings_score'])
print('The range of the scores scored is :',(arr4,arr5))
arr6=np.var(dataset['first_ings_score'])
print('The variance of first inings is ',arr6)
# by using these functions or methods we can get our required statistics from the data.

#4a
dataset['first_ings_score']=dataset['first_ings_score'].sort_values()
dataset['second_ings_score']=dataset['second_ings_score'].sort_values()
dataset.plot('match_id',['first_ings_score','second_ings_score'])
plt.show()
dataset.groupby('venue').size().plot(kind='pie',autopct='%1.2f%%')
plt.show()

# By these means we can create many and various charts for the dataset
# These charts and plots are useful in visualizing the values in the dataset

#5a
arr=pd.crosstab(dataset['toss_winner'],dataset['match_winner'])
sns.heatmap(arr,annot=True,fmt='d')
plt.show()
print('here winning the toss is crucial for winning the game. The teams who who the toss and won the match are in best position compared to the team who lost the toss. The teams winning the toss and electing to bat or field on the pitch report basis is important and performing according to the toss call is also required. ')

#6a
# here date, group are outliers of the dataset
# but they are not useful in finding the matchoutcome but are used in classifying things.

#7a
arr=dataset[['venue','team1','team2','match_winner','player_of_the_match']]
print(arr)
arr1=pd.crosstab(dataset['team1'],dataset['match_winner'])
arr2=pd.crosstab(dataset['team2'],dataset['match_winner'])
sns.heatmap(arr1,annot=True,fmt='d')
plt.show()
sns.heatmap(arr2,annot=True,fmt='d')
plt.show()
#playing at a specific condition make a team comfortable to play, if a team plays in the home groun,. it has an advantage of the audience and pitch awareness.

#8a
arr=dataset['player_of_the_match'].value_counts().head()
print(arr)
arr1=dataset['top_scorer'].value_counts().head()
print(arr1)
arr2=dataset['best_bowling'].value_counts().head()
print(arr2)
print(' Here, Kuldeep yadav has won most player of the match awards in this ipl season. Duw to the spining tracks of the pitch and fielding first most time has given him a perfect opportunity to play upto his best')
print(' As you see, the top_scorer and best_bowling is given to Jos Buttler and yuzvendra chahal respectively. They both are from the same team Rajastha Royals. These persons are one of the reasons why rajasthan has qualified to play the ipl final this season.')

#9a
# by analyzing the dataset , there are no null values in the dataset.
# here to check if the data has any null values or not is necessary before performing any simplification.
# There are no null values in the dataset.
# here every match_id is unique and does not have any duplicate values in the dataset.
# so the dataset is ready for the execution and can be used for any other purposes.
# by using mean,median,min,max,sum functions or methods we can get our required statistics from the data.
# here date, group are outliers of the dataset
# but they are not useful in finding the matchoutcome but are used in classifying things.
# By these means we can create many and various charts for the dataset
# These charts and plots are useful in visualizing the values in the dataset
# This is very useful in specifying seperate columns or tables or plots of our required data.
#