# -*- coding: utf-8 -*-
"""Second_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqSiTwh_eLp6su7EXOQEnSjV4Xf-mSYJ
"""

import pandas as pd
import numpy as np

#1
arr=([1,2,3,4])
print(np.mean(arr))
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

#2
health_data = np.array([[160, 70, 30],   # height, weight, age for individual 1
                        [165, 65, 35],   # height, weight, age for individual 2
                        [170, 75, 40]])  # height, weight, age for individual 3

print(health_data[:,2])
np.mean(health_data[:,2])
np.std(health_data[:,2])

#3
dic={'venkat':[22,23,24,25],'mahesh':[22,25,21,15],'vishal':[22,21,-1,20]}
arr=np.array(dic,ndmin=4)

arr1=np.average(arr)
print(arr1)
#we have to calculate the average of the last

#4
arr=np.linspace(12,25,25)
print(arr)

#5
import numpy as np
daily_closing_prices = np.array([100, 102, 98, 105, 107, 110, 108, 112, 115, 118, 120])
window_size = 5

#6
arr=np.array([[1,0.5],[0.5,2]],ndmin=2)
arr1=np.linspace()
print(arr)

#7
import numpy as np
properties_matrix = np.array([[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]])
arr=np.diagonal(properties_matrix)
print(arr)

#8
arr=([[1,2,3],[4,5,6],[7,8,9]])
arr1=np.array(arr)
print(arr1[arr1>5])

#9
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}

data1=pd.DataFrame(data)

res=data1[(data1['Age']<45) & (data1['Department']!='HR')]
print(res[['Name','City']])

#10
data = {'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
        'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'Sales': [70000, 50000, 30000, 40000, 60000]}

arr=pd.DataFrame(data)
#print(arr)

res=arr.groupby(pd.Grouper(key='Salesperson')).sum()
res

#11
data = {
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': ['True', 'False', 'True', 'True', 'False',' True', 'False']
}

arr=pd.DataFrame(data)
print(arr)
res=arr[(data['Category']=='Fruit') & (data['Price']>3.00)]
print(res)

#12
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
}

# Dataset of employee project assignments
project_data = {
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
}

#13
arr=pd.read_csv('/content/sample_data/Q13_sports_team_stats.csv')
print(arr)

#14
arr=pd.read_csv('/content/sample_data/Q14_customer_purchases.csv')
arr

#15
arr=pd.read_csv('/content/sample_data/Q15_student_grades.csv')
print(arr)